### ISSUE TITLE
Please Add Support For --recipient-file Option

### ISSUE THREAD

**Issue by vsajip** [vsajip/python-gnupg#135]
**[Original report](https://bitbucket.org/vinay.sajip/python-gnupg/issue/135) by Anonymous.**

----------------------------------------

Please add support for --recipient-file option. 

See http://gnupg.10057.n7.nabble.com/New-option-recipient-file-td47916.html

Thanks.

**Comment by markryan-bh** [comment]
> This may not work for all versions of gpg

from the changelog, support was added in version 2.1.14, we could limit the feature to environments with this version or higher.

https://lists.gnupg.org/pipermail/gnupg-announce/2016q3/000393.html

> why can’t you use the extra_args argument to provide the information needed

If you're not using the symmetric flag, the `recipients` param in `encrypt_file()` is required https://github.com/vsajip/python-gnupg/blob/efb2043730b6db890daa20344eea4cd8592c8de6/gnupg.py#L2095-L2097

Ideally, you could provide either `recipients` or `recipient_files` (or both).
