### ISSUE TITLE
default branch on readthedocs.io is stale

### ISSUE THREAD

**Issue by ktdreyer** [vsajip/python-gnupg#168]
The default Read The Docs page links to the "stable" release, rather than "latest". This makes it difficult to find the latest documentation, in particular the latest links to GitHub instead of Bitbucket.

### Steps to reproduce:
1. Visit https://gnupg.readthedocs.io/ in the browser

### Actual results
The page redirects to https://gnupg.readthedocs.io/en/stable/ , with old links to the BitBucket project.

### Expected results:
The page redirects to  https://gnupg.readthedocs.io/en/latest/ , since that properly links to GitHub.

You should be able to change the default branch here: https://readthedocs.org/dashboard/gnupg/advanced/

**Comment by vsajip** [comment]
Thanks for spotting this. It should now be fixed.
