### ISSUE TITLE
Unable to export keys with no passphrase

### ISSUE THREAD

**Issue by winslowdibona** [vsajip/python-gnupg#170]
**Describe the bug**
I am updating a legacy system that has a bunch of keys generated from back in 2016 using `v0.3.8` of this library. I had to update to `v0.4.7` to update the rest of the systems python/django version. The issue is now I cannot export existing pgp keys that were created without a passphrase, since the `export_keys` functionality now requires a password. Is there anyway to  export keys that have no passphrase without having to re-generate all of the existing keys?

**To Reproduce**
1. Generate a pgp key with no passphrase with the 0.3.8 version
2. Attempt to export the key with 0.4.7 and it will fail if no passphrase is provided, providing a random passphrase will result in a incorrect value.

**Comment by vsajip** [comment]
What happens if:

1. You use 0.3.8 to re-export? Or,
2. If you use GnuPG 1.4.x with 0.4.7 or 0.3.8?

**Comment by winslowdibona** [comment]
I was able to get around giving a passphrase by passing in `expect_passphrase=False` when exporting keys and it worked just fine.
