### ISSUE TITLE
GPG_ERROR_CODES reporting "incorrect passphrase" when signing with a key that *has no passphrase*

### ISSUE THREAD

**Issue by phryk** [vsajip/python-gnupg#172]
**Describe the bug**
When using a key generated with `no_protection` to sign, calling `str()` on the result
returns `''` and `GPG_ERROR_CODES` contains 'incorrect passphrase'.

**To Reproduce**
```
key_input = crypto.gen_key_input(key_type='RSA', key_length=4096, no_protection=True)

key = crypto.gen_key(key_input)
…
result = crypto.encrypt("foo", <recipient fingerprint>, sign=key.fingerprint, passphrase=None)
```
I also tried not passing `passphrase` as well as passing `''` for it, same issue.

Adding `gpg-agent.conf` with `allow-loopback-pinentry` to the gpg homedir makes no difference either.

`echo "foo" | gpg --homedir gpg-sender -o - --local-user <sender fingerprint> -as -`
works, yields an ASCII-armored result on stdout and return code 0 – a prompt for the passphrase never appears.

**Expected behavior**
`GPG_ERROR_CODES` should be empty and `str(result)` should return an
ASCII-armored representation of the encrypted and signed input.

**Environment**
 - FreeBSD 12.2
 - Reproduced with module versions 0.4.7 and 0.4.8
 - GnuPG version 2.3.3

**Comment by phryk** [comment]
I just found the time to add passphrases to my code and I *still* get the same error…
Not quite sure what's going on – is this module maybe just plain incompatible with GnuPG 2.3?

**Comment by vsajip** [comment]
> `GPG_ERROR_CODES` should be empty

This is an incorrect assumption. `GPG_ERROR_CODES` is an internal constant lookup table - see [the source](https://github.com/vsajip/python-gnupg/blob/e5f3d7f76cab76229cab3bf3a66979e5800c82d1/gnupg.py#L225-L227). I suggest you turn on logging for the `gnupg` logger and that might help to see what's going on.

> is this module maybe just plain incompatible with GnuPG 2.3?

All the tests pass with GnuPG 2.3 on my Linux system, and I'm not sure why it would behave differently on FreeBSD. I suggest you download the sdist, run the test suite and post your results.

**Comment by phryk** [comment]
Why does GPG_ERROR_CODES always hold the data for an incorrect passphrase?
Far as I can tell, it's never removed.

Running the test suite yields one failed test (with `master` and `0.4.8`):

```
======================================================================
FAIL: test_search_keys (test_gnupg.GPGTestCase)
Test that searching for keys works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/home/phryk/devel/code/python/python-gnupg/test_gnupg.py", line 1275, in test_search_keys
    self.assertEqual(0, r.returncode, 'Non-zero return code')
AssertionError: 0 != 2 : Non-zero return code

----------------------------------------------------------------------
Ran 35 tests in 190.913s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=35 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=35 errors=0 failures=1>
```

Correspondingly, adding a `StreamHandler` to the gnupg logger object yields `gpg returned a non-zero error code: 2`.
The gpg man page doesn't seem to indicate what this exact exit status means, just that it's fatal…

I don't quite understand why this doesn't mess up any other tests, tho – if this is about finding
and loading keys, shouldn't more tests fail?

Additionally, I would like to say that I've kind of resigned to just waiting for sequoia-sop to get official python bindings
because GnuPG is just too much of a garbage fire to use productively, so if this doesn't end up being an obvious or
easy fix, do feel free to take your sweet time as I don't want to pressure anyone into spending time with that eldritch abomination. Thank you for the effort you already put into wrangling this monster in any case. 🙏

**Comment by vsajip** [comment]
> Why does GPG_ERROR_CODES always hold the data for an incorrect passphrase?

It's an internal constant lookup table, not something you need to inspect.

> FAIL: test_search_keys

This test sometimes fails because it relies on external resources (servers which hold information about public keys) which don't always respond in a timely manner. It doesn't mean other tests will necessarily fail - e.g. if they work on local keys.

> GnuPG is just too much of a garbage fire ... Thank you for the effort you already put into wrangling this monster in any case.

You're welcome. I have a companion project, [pagesign](https://github.com/vsajip/pagesign), which provides similar functionality to this project, but using [age](https://age-encryption.org/) for encryption/decryption and [minisign](https://jedisct1.github.io/minisign/) for signing/verification. These are based on more modern cryptographic standards.

**Comment by phryk** [comment]
Alrighty, thanks for your response. :)

Your alternatives do sound interesting, but I'll probably stick to sequoia as that's
something I already have some involvement in and I have need specifically for PGP
in other places, so I'd rather work towards one unified alternative in my infrastructure.

From my end at least this issue can be closed, but as that exit status 2 seems to be completely
reproducible on my system (and according to `man gpg` fatal) I suspect other FreeBSD users
would be affected, too – so it might be good to keep it in mind when future issue reports pop up.

Thanks again for your time.

**Comment by vsajip** [comment]
> as that exit status 2 seems to be completely reproducible on my system

Sure, and on other systems too. There's numerous other issues relating to `gpg` printing an error to stdout/stderr and returning exit status 2, but not returning error information in a parseable way (random error messages can change across `gpg` versions :disappointed: - so not reliably parseable).

**Comment by vsajip** [comment]
I'll close this, as there seems not to be an actual bug in `python-gnupg`.
