### ISSUE TITLE
Support keyserver-options for communication with keyservers

### ISSUE THREAD

**Issue by morco** [vsajip/python-gnupg#173]
Good day,

I'm in the "fortunate" position that my machines lie behind a corporate proxy which makes proper internet access quite complicated. Solving this for keyservers in `gpg` on the cmdline works like this:

   `gpg --batch --keyserver "hkp://keyserver.ubuntu.com:80" --keyserver-options "http-proxy=${HTTP_PROXY}" --recv-keys [...]`

This seems as far as I understand it to be the only way to solve this for `gpg`
as `gpg` does not support to set this per environment variable directly.
Unfortunately it is not possible to use this pattern with this library at the moment, because functions like `recv_keys` simply do not expose any possible way to set keyserver options.

So I'm wondering if you would be interested to add an option to keyserver related functions to optionally pass in keyserver options, something like this:

   `def recv_keys(self, keyserver, *keyids, server_opts=None):`

I would be willing to provide a proper PR for this if this is deemed acceptable in general.

**Comment by vsajip** [comment]
A number of the other APIs (e.g. `encrypt_file()`, `decrypt_file()`) accept an `extra_args` keyword parameter, which can be an array of additional strings (which are appended to the arguments passed to `gpg`). It would be more consistent to use this argument name. I'll look at this soon.

**Comment by vsajip** [comment]
I've now committed 6ad30d6 - see if you can use this to pass server options in `extra_args`, which I've added to `send_keys`, `recv_keys` and `search_keys` - the APIs which interact with keyservers.

**Comment by vsajip** [comment]
Closing, as no feedback received from reporter.
