### ISSUE TITLE
Import x509 certificates

### ISSUE THREAD

**Issue by kuwv** [vsajip/python-gnupg#175]
**Is your feature request related to a problem? Please describe.**

GPG signing can either by GPG based or x509. The x509 signing using s/mime is very common for organizations or people that use smartcards.

**Describe the solution you'd like**

Implement base gpg-agent integration to allow import of x509 certificates.

**Describe alternatives you've considered**

Considering subprocess with TextFSM as an alternative, but this would be as complex as adding this feature to python-gnupg.

**Additional context**

The gpg-agent potentially should also have an API anyway.

**Comment by kuwv** [comment]
This may already be supported. Specifically looking for:
```
gpg-agent --daemon gpgsm --call-protect-tool --p12-import --store key.p12
```

**Comment by vsajip** [comment]
> This may already be supported

It's not, in that `python-gnupg` only wraps the `gpg` executable. I am not aware of any stable API for interacting with `gpg-agent`  (_stable_ as in: works reliably and in pretty much the same way across multiple versions of GnuPG, and across Linux, Windows and macOS). I know that there are mechanisms involving use of `gpg-connect-agent`, `gpgconf` etc. for controlling and communicating with the agent, but it's seemingly not as straightforward as the published API for working with `gpg` as a subprocess.

I want to avoid working on state machines around `gpg` or related executables - upstream doesn't especially care about `python-gnupg` as they have their own approach, and there have been numerous regressions over time which indicate that their regression tests for backward compatibility might be sub-optimal. Even if a solution is produced for a specific version of GnuPG, there's no guarantee that it will work with other versions. I know this from just the variability of just `gpg`'s subprocess interface across versions.

The aversion to potentially brittle state machine implementations is also why key editing functionality is missing from `python-gnupg`, despite requests for it having been made from time to time.

I don't mind looking at a PR around this area but it's too big for me to take it on right now, given the difficulties I allude to above.

**Comment by vsajip** [comment]
I'll close this now as I'm not sure what more can be done, but you can reopen if you have any more relevant information.
