### ISSUE TITLE
Request to operate completely silently

### ISSUE THREAD

**Issue by SwampFalc** [vsajip/python-gnupg#177]
**Is your feature request related to a problem? Please describe.**
It bothers me that, when errors occur, they are directly printed to the console. I understand that this would be desirable for certain use cases, but for mine, where I use this package mostly as a library, it is not.

**Describe the solution you'd like**
I would like an option to use this packaging completely silently, ie. nothing ever gets printed to the console. Much work has already been done to add the `returncode` attribute to what gets returned from gpg calls, so I already have everything I need to produce the output I need, as long as I can silence this package.

**Describe alternatives you've considered**
I am aware that the printing occurs through the use of the stdlib `logging` module and that it should be possible for me to completely silence it, as a workaround. I feel that an integrated solution would be better.

**Additional context**
I noticed #176 opened just a short while ago (pure coincidence) and while my request does go in the same direction, I felt it would muddle the discussion if I just posted my request in the same thread.

**Comment by vsajip** [comment]
Logging doesn't print anything unless configured to do so - so if you are seeing console output from logging, it's because _something_ has configured it to do that. Please post a minimal script demonstrating the problem, but AFAIK there are no `print` calls in `python-gnupg` except when I'm debugging stuff.

**Comment by SwampFalc** [comment]
Hmmm...

I think the culprit might simply be `pytest`. From their own documentation: "pytest captures log messages of level WARNING or above automatically".

In that case, this request may be closed. I will silence logging in my unittests for the moment, and I will keep an eye on #176 since work on that will probably leave me with a slightly cleaner solution.
