### ISSUE TITLE
Info around BrokenPipeError

### ISSUE THREAD

**Issue by fvukojevic** [vsajip/python-gnupg#182]
**Is your feature request related to a problem? Please describe.**

I have just a simple question, probably not needing any code changes. It's around handling `BrokenPipeError`. I am not 100% sure when and how it happens, but every once in a while it get's thrown. 

I am just wondering if I can catch if on the top level call of `encrypt` method? 

Hoping to do something like 

```
    try:
        _get_gpg().encrypt(data=data, recipients=fingerprint).data
    except BrokenPipeError as bpe:
        raise EncryptionConfigurationError(
            f"Unable to encrypt data: {data}. Failed with following message: {str(bpe)}"
        )
```

Just want to make sure if this can work, because I'm afraid of exception swallowing due to this running on separate process because of Streams, etc

**Comment by vsajip** [comment]
Well, if you are seeing a `BrokenPipeError` in your Python process, that means you _should_ be able to catch it in your Python code.
