### ISSUE TITLE
FAILURE value is not a key-id

### ISSUE THREAD

**Issue by sebbASF** [vsajip/python-gnupg#183]
PR #180 prevented FAILURE messages from overwriting the key_id:

https://github.com/vsajip/python-gnupg/blob/0dab09084ad49466356de3f401e92062d99ef314/gnupg.py#L337

As far as I can tell, the value that is associated with the FAILURE key is not a key-id, so should never be used to set the key_id.
So whilst the PR fixed the immediate issue, the key_id could still end up with an invalid value.

I don't know whether the UNEXPECTED message value can be a key_id.

**Comment by vsajip** [comment]
Closed in #187.
