### ISSUE TITLE
Verify does not handle missing sig data well

### ISSUE THREAD

**Issue by sebbASF** [vsajip/python-gnupg#191]
This relates to detached signature verification:

If the .asc file is empty, verification fails, and the status is set to 'error - verify 4294967295'

That is OK, although the status is not very helpful.
However, if the asc file contains some text (but is not a valid sig), then verification fails and status is not set.
This does not seem right.
If debug is enabled, the following messages are shown:

[GNUPG:] NODATA 3
message ignored: NODATA, 3
[GNUPG:] NODATA 4
message ignored: NODATA, 4
gpg: no signature found
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
gpg returned a non-zero error code: 2

I think it would be useful to process the NODATA messages.
The value 3 means 'Invalid packet found'; 4 means 'Signature expected but not found'
Either of those would be better as a status than None.

**Comment by vsajip** [comment]
Makes sense.

**Comment by sebbASF** [comment]
I think the other NODATA values also need to be handled, as they can also be generated.

It looks like there are 3 different responses at least:
- .asc file length 0 => NODATA 2 followed by FAILURE verify 4294967295
- .asc file length 1 => NODATA 3 and NODATA 4
- .asc file length > 1 => NODATA 1 and NODATA 2

The last case is not yet handled.

Two more cases that should now be picked up:
- .asc file contains just the BEGIN/END markers => NODATA 3, NODATA 4, NODATA 1
- .asc file contains a truncated signature between valid markers => NODATA 1, NODATA 3, NODATA 4

**Comment by vsajip** [comment]
It seems simplest to not worry about the 1, 2, 3 etc. (as they appear pretty unhelpful) and treat all `NODATA` as "signature expected but not found". The `FAILURE` can leave the status alone if it's already set to "signature expected but not found".

**Comment by sebbASF** [comment]
OK. The main thing is to ensure that the status is not left as None.
