### ISSUE TITLE
Method to dump Verify properties

### ISSUE THREAD

**Issue by sebbASF** [vsajip/python-gnupg#192]
When testing, one often needs to display the values the Verify class properties, e.g. status, key_id, key_status etc.

It would be useful to have a method to dump them all.

Alternatively, maybe a method to bundle them up as a dict, in which case they can be shown with print or pprint.

[The same applies to subclasses of Verify]

**Comment by vsajip** [comment]
Why can't you just dump `verify_object.__dict__`?

**Comment by sebbASF** [comment]
Doh!
