### ISSUE TITLE
How can I create an ECC  key?

### ISSUE THREAD

**Issue by leifliddy** [vsajip/python-gnupg#193]
By default ```gpg2``` will create the following type of key

```
Please select what kind of key you want:
...
   (9) ECC (sign and encrypt) *default*
...
Please select which elliptic curve you want:
   (1) Curve 25519 *default*
   (4) NIST P-384
```
```
pub   ed25519 2022-08-16 [SC]
      AE25598755FB9C3E5B183C81C995DB8820E78094
uid           [ultimate] test user <test@localhost>
sub   cv25519 2022-08-16 [E]
```
However, I can't seem to create this type of key with this library. 
So I looks like I should be able to generate this type of key with the ```ECDH``` algorithm
```
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
```

But, providing these values to ```gen_key_input``` doesn't seem to work.
```
key_type='ECDH', key_curve='cv25519'
```
I can dig through the code later, just wondering if someone would know off the top of their head how to create the default key-type that ```gpg2``` generates.

**Comment by leifliddy** [comment]
I'm such an idiot -- I found the solution right after posting this
So I need to provide these values:
```
key_type='EDDSA', key_curve='ed25519'
```
Perhaps the documentation could be updated to show how to do this.

**Comment by vsajip** [comment]
It is documented [here](https://docs.red-dove.com/python-gnupg/index.html#generating-elliptic-curve-keys) and [here](https://gnupg.readthedocs.io/en/latest/#generating-elliptic-curve-keys).

**Comment by leifliddy** [comment]
Sure...how to create an elliptic curve key is listed, but the terms ```EDDSA``` or ```ed25519``` never appear in that documentation

I just don't think most people are going to make the leap   
from this:  
```
Please select what kind of key you want:
...
   (9) ECC (sign and encrypt) *default*
...
Please select which elliptic curve you want:
   (1) Curve 25519 *default*
````
to this:  
```
input_data = gpg.gen_key_input(key_type='EDDSA', key_curve='ed25519' ...
master_key = gpg.gen_key(input_data)
subkey = gpg.add_subkey(master_key.fingerprint, algorithm='cv25519' ...
```
That's all I'm saying. You would really have to understand gpg keys in order to follow that. I suppose it might be better if the ```gpg``` command listed the actual algorithm, rather then just ```ECC``` so one could make a direct correlation between creating a key with ```gpg``` and creating one with ```python-gnugpg```
