### ISSUE TITLE
request to add documentation for RSA subkey size

### ISSUE THREAD

**Issue by leifliddy** [vsajip/python-gnupg#195]
So the documentation currently shows the following for ```add_subkey```:
```
The add_subkey method has some additional keyword arguments:

algorithm (defaulting to rsa)
usage (defaulting to encrypt)
expire (defaulting to -)
```

But it doesn't show how to request an RSA key of a specific size.   
The default RSA key size is dependent upon the version of ```gpg``` installed.   
So it's useful to know how to specify the key size. 

The RSA key size can easily be defined via the following notation:
```
gpg.add_subkey(..., algorithm='rsa2048')
gpg.add_subkey(..., algorithm='rsa3072')
gpg.add_subkey(..., algorithm='rsa4096')
```
Could you please include that in your documentation?

**Comment by vsajip** [comment]
Sure, I'll do that.
