### ISSUE TITLE
Add delete_passphrase_cache() method to gpg

### ISSUE THREAD

**Issue by RachitSharma2001** [vsajip/python-gnupg#202]
**Is your feature request related to a problem? Please describe.**
I had recently been using python-gnupg for doing pgp encryption on a host server. For security reasons, I did not want to have keys or passphrases stored on disk in the long term. However, I found that whenever I performed decryption using an imported key and passphrase, the passphrase would be "cached" onto the server. As a result, after only one successful decryption, all later decryptions would be successful even if the passphrase was incorrect. This not only made the software vulnerable to incorrect behavior, but it also made it insecure, as any hacker could get access to the decryption passphrase just by getting access to the server. 

**Describe the solution you'd like**
There is already a [delete_keys()](https://gnupg.readthedocs.io/en/latest/#deleting-keys) function that deletes any imported gpg key. I would like to introduce a delete_passphrase_cache() function that, in a similar way, deletes any cached passphrase. Ex:
```
fp = key.fingerprint
gpg.delete_keys(fp)
gpg.delete_passphrase_cache(fp)
```

**Describe alternatives you've considered**
In the documentation [here](https://gnupg.readthedocs.io/en/latest/#decryption), it explains that passphrase caching can be prevented all together by just modifying **gpg-agent.conf**. However, what if the program is running on a machine different from our own, where modifying this file is not trivial or not even allowed? It would be much more convenient, and allow much more flexibility to developers, if some function was present which allowed for the deletion of the passphrase cache. 

**Additional context**
**I am willing to submit a PR to implement this feature.**

**Comment by vsajip** [comment]
What method do you envisage using to implement the feature? `python-gnupg` interacts with `gpg` on the local machine using local resources (including `gpg-agent.conf`), right?

**Comment by RachitSharma2001** [comment]
My idea is to delete the passphrase that is cached in the path `~/.gnupg`. Also, to clarify my idea for this feature, lets say we are triggering a container that runs python-gnupg to decrypt some files. This container will run on some cloud server that we have no control over, and thus it is not trivial nor is it likely possible to be able to disable passphrase caching through editing `gpg-agent.conf`. So instead, I thought it might be useful to allow users to delete any passphrase cache's that form on the computer system after decryption occurs.

**Comment by vsajip** [comment]
But won't the relevant `~/.gnupg` be on the same computer where you find `gpg-agent.conf`?

**Comment by vsajip** [comment]
Also, it seems premature to make this change unless the present state of the code is causing an _actual_ (rather than a theoretical) problem.

**Comment by RachitSharma2001** [comment]
That is a good point, I've realized that this feature was probably only needed for my specific implementation but may be confusing and lead to errors if used by other users. I will close this issue.
