### ISSUE TITLE
All keys disappear on newer versions of GPG due to spurious creation of `pubring.gpg` file

### ISSUE THREAD

**Issue by metov** [vsajip/python-gnupg#207]
Attempting to use python-gnupg (e.g. `gpg = gnupg.GPG()`) creates some junk files in the GPG home dir, which makes all GPG keys disappear from the output of `gpg --list-keys`.

From what I can tell:
* GPG decided to switch their storage format
* Instead of `$GNUPGHOME/pubring.gpg`, they now store the keys in `$GNUPGHOME/private-keys-v1.d/`
* If a `pubring.gpg` file exists, GPG ignores `private-keys-v1.d/`

python-gnupg is evidently not up to date with this change, because trying to use it with a recent version of GPG (that does not create the `pubring.gpg` file) causes this file to be created empty (a 32 byte file).

Thereafter, when you run `gpg`, it sees the `pubring.gpg` and assumes the legacy storage format is being used. Therefore `private-keys-v1.d/` is ignored from that point on, and when you try to do `gpg --list-keys` all keys appear gone.

Deleting the 32 byte `pubring.gpg` file solve the problem for `gpg`. python-gnupg of course creates it again the next time it's used.

This reddit post talks about the same problem: https://old.reddit.com/r/GnuPG/comments/k13dgj/gnupg_suddenly_not_reading_keys/

The expected behavior would be that if `private-keys-v1.d/` exists and is used, python-gnupg should refrain from creating an empty `pubring.gpg`. It should ideally use the keys from `private-keys-v1.d/`, or failing that, at least crash with an error about how the new storage format is not supported.

**Comment by metov** [comment]
Looking more closely at the [manual page](https://man.archlinux.org/man/gpg.1) for GPG v2.2.39, the section under `~/.gnupg/pubring.gpg` says:

>The public keyring using a legacy format. You should backup this file.
>
>If this file is not available, gpg defaults to the new keybox format and creates a file ‘pubring.kbx’ unless that file already exists in which case that file will also be used for OpenPGP keys.
>
>Note that in the case that both files, ‘pubring.gpg’ and ‘pubring.kbx’ exists but the latter has no OpenPGP keys, the legacy file ‘pubring.gpg’ will be used. Take care: GnuPG versions before 2.1 will always use the file ‘pubring.gpg’ because they do not know about the new keybox format. In the case that you have to use GnuPG 1.4 to decrypt archived data you should keep this file.
```

In my case, indeed `pubring.kbx` exists and is several kB large, while `pubring.gpg` does not exist (unless erroneously created by python-gnupg).

So I'm guessing the solution is probably to make python-gnupg check for `pubring.kbx` before creating `pubring.gpg` when the GPG version is >2.1.

**Comment by vsajip** [comment]
I don't think this is a `python-gnupg` issue - it doesn't create any keyring files itself, it leaves all that to `gpg`. This seems like it's just a transition/migration issue relating to `gpg`. If you haven't already, you'll need to do a one-off transition of the key data into new formats.

**Comment by metov** [comment]
> you'll need to do a one-off transition of the key data into new formats.

I'm not sure I follow.

If I'm not mistaken, the newest format is `private-keys-v1.d/`, and this is already what I'm using. When I run the `gpg` command line program, it happily uses `private-keys-v1.d/` and does not create a spurious `pubring.gpg` file.

Only `python-gnupg` seems to create it.

> it doesn't create any keyring files itself, it leaves all that to `gpg`

That makes sense - but doesn't that mean that when I run `gpg` it should also create the `public.gpg` file (it doesn't)? Could it be that `python-gnupg` is calling `gpg` with some legacy format arguments?

**Comment by vsajip** [comment]
> Could it be that python-gnupg is calling gpg with some legacy format arguments?

Not that I know of - though we still support `gpg 1.4.x`. If you turn on logging, you'll see the exact `gpg` commands that `python-gnupg` invokes. If you spot something specific there that you think is problematic, I'll take a look.

**Comment by vsajip** [comment]
In a fresh environment with GnuPG 2.2.27, if I run a script using `python-gnupg` to make some keys in a fresh `keys` subdirectory - using `gpg = gnupg.GPG(gnupghome='keys')` - I find the contents of `keys` to be as expected:
```
$ ls keys
openpgp-revocs.d   pubring.kbx~     S.gpg-agent.extra
private-keys-v1.d  S.gpg-agent      S.gpg-agent.ssh
pubring.kbx    S.gpg-agent.browser  trustdb.gpg
```
