### ISSUE TITLE
INV_RECP status code support request

### ISSUE THREAD

**Issue by leifliddy** [vsajip/python-gnupg#208]
It would be really useful if we could see the actual ```INV_RECP``` status messages vs simply displaying the generic `invalid recipient` message.

```python
  elif key == 'INV_RECP':  # pragma: no cover
      self.status = 'invalid recipient'
```

The status codes + messages can be found here:
https://github.com/gpg/gnupg/blob/master/doc/DETAILS#inv_recp-inv_sgnr

I'm working on a project and it would insanely useful for me to see these status messages returned. Without the ```always-trust``` arg, a key needs to be ```ultimately``` trusted in order to encrypt something....and If the result status returned is ```Key not trusted``` (which corresponds to ```INV_RECP 10```) then I know exactly what the issue is and how to handle it. 

```
DEBUG:gnupg:[GNUPG:] KEY_CONSIDERED 8D2D438B13429DAA19AD116EBCC794837416F045 0
DEBUG:gnupg:[GNUPG:] KEY_CONSIDERED 8D2D438B13429DAA19AD116EBCC794837416F045 0
DEBUG:gnupg:gpg: BCFDACAB3D66F4CE: There is no assurance this key belongs to the named user
DEBUG:gnupg:[GNUPG:] INV_RECP 10 packaging@saltstack.com
DEBUG:gnupg:[GNUPG:] FAILURE encrypt 53
```

I could implement this change if you want, but I'm pretty sure have your own way of doing things. There's only 15 status codes, so it shouldn't take a ridiculous amount of effort. 

Also, I really want to thank you for maintaining such a cool and useful project!!!

**Comment by vsajip** [comment]
Hmmm - that may break people's code who are relying (rightly or wrongly) on `'invalid recipient'`. I could add an additional `status_detail` attribute which holds the additional information - that should work, right?

**Comment by leifliddy** [comment]
Sure, that would work. Thanks!

**Comment by vsajip** [comment]
I've implemented and committed it, but not yet added a test. Could you please check if the enhancement works, and report back here? It'd be good to get any wrinkles ironed out before the next release (which is not for a little while, as currently planned).

**Comment by leifliddy** [comment]
Sure no prob. I'll test it out tonight.

**Comment by leifliddy** [comment]
This 
```python
def _determine_invalid_recipient_or_signer(s):
    code, ident = s.split()
    unexpected = 'unexpected return code %r' % code
    try:
        key = int(s)
```
should be 

```python
def _determine_invalid_recipient_or_signer(s):
    code, ident = s.split()
    unexpected = 'unexpected return code %r' % code
    try:
        key = int(code)
```

**Comment by leifliddy** [comment]
gpg is not behaving in the way I would expect. I've tried revoking, disabling, expiring.....etc keys.   
But it almost always returns this generic error message ```INV_RECP 0```

One test I performed -- I created a key pair that didn't have the ```sign``` key usage
```
pub   rsa3072 2022-10-13 [CA]
      E8C2F38FA3C9C1971F770965448056A532406889
uid           [ultimate] packager integrity <packager@localhost>
sub   rsa3072 2022-10-13 [E]
```

So when I tried to sign a file the following error message was returned
```DEBUG:gnupg:[GNUPG:] INV_SGNR 9```
But because it doesn't have a key associated with it there's no ```ident``` value.
So I had to modify this function to account for that. 


```diff
 def _determine_invalid_recipient_or_signer(s):
-    code, ident = s.split()
+    ident = None
+    try:
+        code, ident = s.split()
+    except:
+        code = s
+    
     unexpected = 'unexpected return code %r' % code
     try:
-        key = int(s)
+        key = int(code)
         result = _INVALID_KEY_REASONS.get(key, unexpected)
     except ValueError:
         result = unexpected
-    return '%s: %s' % (result, ident)
+    
+    if ident:
+        return '%s: %s' % (result, ident)
+    else:
+        return result
```

There were other ```copy_data``` errors that were produced by trying to do this (but these errors predate this change)
```DEBUG:gnupg:[GNUPG:] FAILURE sign 54
WARNING:gnupg:potential problem: FAILURE: sign 54
ERROR:gnupg:Error sending data
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gnupg.py", line 155, in _copy_data
    outstream.write(data)
BrokenPipeError: [Errno 32] Broken pipe
DEBUG:gnupg:gpg: signing failed: Unusable secret key
WARNING:gnupg:Exception occurred while closing: ignored
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gnupg.py", line 164, in _copy_data
    outstream.close()
BrokenPipeError: [Errno 32] Broken pipe
DEBUG:gnupg:closed output, 69632 bytes sent
WARNING:gnupg:gpg returned a non-zero error code: 2
result.status: invalid signer
result.status_detail: not a secret key
```

######################################################################################

Another issue arises when you try to encrypt a file with an expired key 
```
DEBUG:gnupg:[GNUPG:] KEYEXPIRED 1665702183
DEBUG:gnupg:[GNUPG:] KEY_CONSIDERED E9D24B5CD16925C55E380911D0EC1E549F301C52 0
DEBUG:gnupg:gpg: error retrieving 'packager@localhost' via WKD: Connection refused
DEBUG:gnupg:gpg: packager@localhost: skipped: Connection refused
DEBUG:gnupg:[GNUPG:] INV_RECP 0 packager@localhost
DEBUG:gnupg:[GNUPG:] FAILURE encrypt 167804953
DEBUG:gnupg:gpg: [stdin]: encryption failed: Connection refused
WARNING:gnupg:gpg returned a non-zero error code: 2
DEBUG:gnupg:encrypt result[:100]: b''
result.status: invalid recipient
result.status_detail: no specific reason given: packager@localhost
```
Here the generic ```INV_RECP 0``` ```no specific reason given``` error is returned (who knows why)   
and because ```gnupg.py``` is looking for ```INV_RECP``` before ```KEYEXPIRED``` --  the much more useful ```key expired``` error message isn't returned.
```python
        elif key == 'INV_RECP':  # pragma: no cover
            self.status = 'invalid recipient'
            self.status_detail = _determine_invalid_recipient_or_signer(value)
        elif key == 'KEYEXPIRED':  # pragma: no cover
            self.status = 'key expired'
```
 I just realized that that's a separate issue. You might want to move  that ```elif key == 'INV_RECP':``` check to the very bottom of those checks. 

This isn't nearly as useful as I though it was going to be. As I said, I ran through a battery of tests and all but two returned that ```INV_RECP 0``` error. The only really useful error code that seems to be produced is that ```INV_RECP 10``` ```Key not trusted``` error. I suppose that ```INV_SGNR 9``` error might have some value for certain rare edge cases. 

However, it doesn't hurt anything to leave those changes in....but as I said, I would just move ```elif key == 'INV_RECP':``` to the bottom (or near the bottom) of those elif checks as an expired key or expired signature would seem to have a higher priority then an invalid recipient. 
Anyways, I hope this helps.

**Comment by vsajip** [comment]
> key = int(code)

Yes, that's right - whoops!

```diff
-    code, ident = s.split()
+    ident = None
+    try:
+        code, ident = s.split()
+    except:
+        code = s
```
It might be neater to do
```python
parts = s.split()
if len(parts) >= 2:
    code, ident = parts[:2]
else:
    code = parts[0]
    ident = '<no ident>'
```
> you might want to move that `elif key == 'INV_RECP':` check to the very bottom of those checks

That will just overwrite the `status`, which we don't necessarily want. I think the position of the check can stay as is, but the `status` should only be overwritten if it's not already been set.

I'll make these changes anyway.

On the other stuff (broken pipes, inexplicable return `INV_RECP 0` for an expired key) it might be worth [flagging an issue upstream with the GnuPG project](https://dev.gnupg.org/maniphest/task/edit/form/3/).

**Comment by vsajip** [comment]
Oh, and thanks for the test report!

**Comment by leifliddy** [comment]
Ahhh ok I see how ```status``` would have been overwritten. I wasn't even thinking of the fact that this message
```DEBUG:gnupg:[GNUPG:] KEYEXPIRED 1665702183```   
occurred _before_
```DEBUG:gnupg:[GNUPG:] INV_RECP 0 packager@localhost```

Looks good!
This might seem really trivial, but just want to confirm that you wanted to 
remove the space after this colon. 

```diff
         result = _INVALID_KEY_REASONS.get(key, unexpected)
     except ValueError:
         result = unexpected
-    return '%s: %s' % (result, ident)
+    return '%s:%s' % (result, ident)
```

**Comment by vsajip** [comment]
> but just want to confirm that you wanted to remove the space after this colon

Yes, it was added by mistake. The documentation change refers to `reason:ident` and not having the space allows splitting `reason` and `ident` neatly, if anyone needs to.
