### ISSUE TITLE
`sig_info` with multiple signatures is broken when an invalid/unverified signature is included

### ISSUE THREAD

**Issue by lkubb** [vsajip/python-gnupg#214]
**Describe the bug**
When multiple signatures are parsed and one of them – except the first – is invalid, `sig_info` will contain incorrect information for the valid ones. More specifically, the `keyid`, `username` and `status` for the previously parsed signature will be overwritten.

This is caused by `gpg` not outputting a SIG_ID for invalid signatures and `sig_info` being indexed by them.

Edit: This also seems to be the case for signatures that do not have a public key in the keyring. They additionally overwrite `fingerprint`, which makes this even more an issue. Even if you rely on `trust_level` and `fingerprint`, this means a valid signature followed by one created by a public key that is not present in the keyring would lead to a situation where you mistake the valid signature's `trust_level` output for the output of the unverified one.

**To Reproduce**
1. create two keys
2. sign differing data with each
3. concatenate the resulting signatures
4. `res = gpg.verify_file(...)`
5. `assert len(res["sig_info"]) == 2` will fail

or this script:

```python
import gnupg


o = """\
[GNUPG:] NEWSIG
gpg: Signature made Thu Dec  1 00:23:09 2022 UTC
gpg:                using RSA key EF03765F59EE904930C8A781553A82A058C0C795
[GNUPG:] KEY_CONSIDERED EF03765F59EE904930C8A781553A82A058C0C795 0
[GNUPG:] SIG_ID 4gygTT2HAmCYrLpeAgBPYo3egRU 2022-12-01 1669854189
[GNUPG:] KEY_CONSIDERED EF03765F59EE904930C8A781553A82A058C0C795 0
[GNUPG:] GOODSIG 553A82A058C0C795 Key A (Generated by SaltStack) <keya@example>
gpg: Good signature from "Key A (Generated by SaltStack) <keya@example>" [ultimate]
[GNUPG:] VALIDSIG EF03765F59EE904930C8A781553A82A058C0C795 2022-12-01 1669854189 0 4 0 1 8 00 EF03765F59EE904930C8A781553A82A058C0C795
[GNUPG:] TRUST_ULTIMATE 0 pgp
[GNUPG:] NEWSIG
gpg: Signature made Thu Dec  1 00:34:47 2022 UTC
gpg:                using RSA key 96F136AC4C92D78DAF33105E35C03186001C6E31
[GNUPG:] KEY_CONSIDERED 96F136AC4C92D78DAF33105E35C03186001C6E31 0
[GNUPG:] KEY_CONSIDERED 96F136AC4C92D78DAF33105E35C03186001C6E31 0
[GNUPG:] BADSIG 35C03186001C6E31 Key C (Generated by SaltStack) <keyc@example>
gpg: BAD signature from "Key C (Generated by SaltStack) <keyc@example>" [ultimate]"""


v = gnupg.Verify(gnupg.GPG())

for line in o.splitlines():
    if line[0:9] == "[GNUPG:] ":
        # Chop off the prefix
        line = line[9:]
        L = line.split(None, 1)
        keyword = L[0]
        if len(L) > 1:
            value = L[1]
        else:
            value = ""
        v.handle_status(keyword, value)

print("=================================")
print("Final result:")
print(v.__dict__)
print("Number of entries: " + str(len(v.sig_info)))
print(
    "Status of good signature: "
    + next(
        x["status"]
        for x in v.sig_info.values()
        if x["fingerprint"] == "EF03765F59EE904930C8A781553A82A058C0C795"
    )
)
```

Use this vector for the second case:
```
[GNUPG:] NEWSIG
gpg: Signature made Thu Dec  1 00:23:09 2022 UTC
gpg:                using RSA key EF03765F59EE904930C8A781553A82A058C0C795
[GNUPG:] KEY_CONSIDERED EF03765F59EE904930C8A781553A82A058C0C795 0
[GNUPG:] SIG_ID 4gygTT2HAmCYrLpeAgBPYo3egRU 2022-12-01 1669854189
[GNUPG:] KEY_CONSIDERED EF03765F59EE904930C8A781553A82A058C0C795 0
[GNUPG:] GOODSIG 553A82A058C0C795 Key A (Generated by SaltStack) <keya@example>
gpg: Good signature from "Key A (Generated by SaltStack) <keya@example>" [ultimate]
[GNUPG:] VALIDSIG EF03765F59EE904930C8A781553A82A058C0C795 2022-12-01 1669854189 0 4 0 1 8 00 EF03765F59EE904930C8A781553A82A058C0C795
[GNUPG:] TRUST_ULTIMATE 0 pgp
[GNUPG:] NEWSIG
gpg: Signature made Thu Dec  1 13:36:31 2022 UTC
gpg:                using RSA key D7D3F617EBD2113059914876F7D0B975BC8E7ED1
[GNUPG:] ERRSIG F7D0B975BC8E7ED1 1 8 00 1669901791 9 D7D3F617EBD2113059914876F7D0B975BC8E7ED1
[GNUPG:] NO_PUBKEY F7D0B975BC8E7ED1
gpg: Can't check signature: No public key
```

**Expected behavior**
Either exclude bad/unverified signatures from `sig_info` or make sure they do not overwrite valid ones (make `sig_info` a list and rely on `NEWSIG`, for example).

**Screenshots**
```
=================================
Final result:
{'gpg': <gnupg.GPG object at 0x100b5ada0>, 'valid': False, 'fingerprint': 'EF03765F59EE904930C8A781553A82A058C0C795', 'creation_date': '2022-12-01', 'timestamp': '1669854189', 'signature_id': '4gygTT2HAmCYrLpeAgBPYo3egRU', 'key_id': '35C03186001C6E31', 'username': 'Key C (Generated by SaltStack) <keyc@example>', 'key_status': None, 'status': 'signature bad', 'pubkey_fingerprint': 'EF03765F59EE904930C8A781553A82A058C0C795', 'expire_timestamp': '0', 'sig_timestamp': '1669854189', 'trust_text': 'TRUST_ULTIMATE', 'trust_level': 4, 'sig_info': {'4gygTT2HAmCYrLpeAgBPYo3egRU': {'creation_date': '2022-12-01', 'timestamp': '1669854189', 'keyid': '35C03186001C6E31', 'username': 'Key C (Generated by SaltStack) <keyc@example>', 'status': 'signature bad', 'fingerprint': 'EF03765F59EE904930C8A781553A82A058C0C795', 'expiry': '0', 'pubkey_fingerprint': 'EF03765F59EE904930C8A781553A82A058C0C795', 'trust_level': 4, 'trust_text': 'TRUST_ULTIMATE'}}}
Number of entries: 1
Status of good signature: signature bad
```

Second case sig_info:
```console
>>> v.sig_info
{'4gygTT2HAmCYrLpeAgBPYo3egRU': {'creation_date': '2022-12-01', 'timestamp': '1669901791', 'keyid': 'F7D0B975BC8E7ED1', 'username': 'Key A (Generated by SaltStack) <keya@example>', 'status': 'signature error', 'fingerprint': 'D7D3F617EBD2113059914876F7D0B975BC8E7ED1', 'expiry': '0', 'pubkey_fingerprint': 'EF03765F59EE904930C8A781553A82A058C0C795', 'trust_level': 4, 'trust_text': 'TRUST_ULTIMATE'}}
```

**Environment**
 - macOS Monterey
 - gpg 2.3.8
 - python-gnupg 0.4.8

**Comment by vsajip** [comment]
Thanks for the report. I think my fix should work (it has to work with `gpg` 1.x as well as 2.x), but please confirm.

**Comment by lkubb** [comment]
Thanks for the astoundingly fast response! I can confirm this works for `gpg` v2 [if the intention is to only include valid signatures in `sig_info`].

**Comment by vsajip** [comment]
> if the intention is to only include valid signatures in `sig_info`

Well, I'm not sure what useful information could be gleaned from invalid signatures - `gpg` doesn't really return much useful information. It's possible we could collect that information under e.g. a `bad_signatures` attribute, but it doesn't belong in `sig_info` IMO.

**Comment by lkubb** [comment]
I agree, just wanted to point out the difference in behavior. Maybe it should be explicitly documented that `sig_info` only contains cryptographically valid signatures.

Information about missing pubkeys or bad signatures might be interesting in some cases nonetheless, but that's a different issue. Thanks once again for your rapid response, very much appreciated :)

**Comment by vsajip** [comment]
> Maybe it should be explicitly documented that `sig_info` only contains cryptographically valid signatures.

Yes, I'll add a note to that effect.
