### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe getting this error when encrypting files.

### ISSUE THREAD

**Issue by Hamza442** [vsajip/python-gnupg#215]
python-gnupg=0.3.6
I am encrypting files using:

 gpg = gnupg.GPG(gnupghome=temp_directory)
 gpg.encoding = 'utf-8'
 
  with open(filepath,'rb') as input_file:
      gpg.encrypt_file(
                    input_file,
                    recipients,
                    always_trust=True,
                    output=encrypted_filepath,
                    armor=False,
                ) 
                
 **ERROR**
 
 [ERROR] gnupg: Error sending data
 
 18:03:05+00:00 Traceback (most recent call last):
18:03:05+00:00   File "/var/lib/jenkins/workspace/analytics-exporter-master/exporter_venv/lib/python3.8/site-packages/gnupg.py", line 128, in _copy_data
18:03:05+00:00     outstream.write(data)
18:03:05+00:00 BrokenPipeError: [Errno 32] Broken pipe
18:03:05+00:00 2022-12-05 18:03:05,093 [WARNING] gnupg: Exception occurred while closing: ignored
18:03:05+00:00 Traceback (most recent call last):
18:03:05+00:00   File "/var/lib/jenkins/workspace/analytics-exporter-master/exporter_venv/lib/python3.8/site-packages/gnupg.py", line 137, in _copy_data
18:03:05+00:00     outstream.close()
18:03:05+00:00 BrokenPipeError: [Errno 32] Broken pipe

any solution to this issue ??

**Comment by vsajip** [comment]
Well, it's not actually causing a problem, is it? One could omit the logging, I suppose. The broken pipe exception is logged, but swallowed, isn't it?

**Comment by Hamza442** [comment]
@vsajip yes this causing problem, so usually when it runs successfully without this error it creates encrypted files, but due to this error it's not creating those files.

**Comment by vsajip** [comment]
You are using a pretty old version of `python-gnupg` - the current version is `0.5.0`. What result do you get with that? Also, what version of GnuPG is being used?

**Comment by Hamza442** [comment]
@vsajip with version **0.5.0**,  I get following warning 

`[WARNING] gnupg: gpg returned a non-zero error code: 2`

Don't see broken pipe here with latest version but the issue still persist the files don't get encrypted 

Gnupg : `gpg (GnuPG) 1.4.20`

**Comment by vsajip** [comment]
Can you run the test suite which comes with the source? (`test_gnupg.py`) and confirm if all the tests pass?

**Comment by vsajip** [comment]
You should enable stdlib logging for `gnupg` module and see what it shows in the log.

**Comment by Hamza442** [comment]
@vsajip can you share a link to test suite

**Comment by vsajip** [comment]
It's in this repository

**Comment by Hamza442** [comment]
@vsajip just a quick question , let say if key was generated using GNUPG version 2 and we are on version 1.4.20 does this can cause any issue ?

**Comment by vsajip** [comment]
Yes, it might. Best to ask the GnuPG project for absolute confirmation.

**Comment by Hamza442** [comment]
@vsajip I run test once with your **KEYS_TO_IMPORT** parameter and one test failed and then I repaced your key with mine and 7 test failed not sure what this indicates

**Comment by vsajip** [comment]
Just run the _unmodified_ test suite using `python test_gnupg.py` and look at `test_gnupg.log` that it produces. All the `gpg` commands that are run by the tests are in the log. If a specific test fails, post the section of the log corresponding to the failing test. Duplicate those commands replacing the test ones with your specific keys etc. and see what you find. I can't really spend a lot of time looking at your specific stuff in detail (as I don't have the time to spend); if you produce a short standalone script which demonstrates a problem I'll take a look at it. Look at closed issues in this repo - the ones marked "invalid" aren't actual issues, the others raised actual problems or suggested improvements.

**Comment by Hamza442** [comment]
Result with unmodified test suit
`...................................F...
======================================================================
FAIL: test_search_keys (__main__.GPGTestCase)
Test that searching for keys works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gnupg.py", line 1247, in test_search_keys
    self.assertEqual(0, r.returncode, 'Non-zero return code')
AssertionError: 0 != 2 : Non-zero return code

----------------------------------------------------------------------
Ran 39 tests in 74.077s

FAILED (failures=1)`

**Result with modified test suit**

`..F.......FF..................F..FFF...
======================================================================
FAIL: test_deletion (__main__.GPGTestCase)
Test that key deletion works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gnupg.py", line 1042, in test_deletion
    self.assertTrue(is_list_with_len(public_keys, 2), '2-element list expected')
AssertionError: 2-element list expected

======================================================================
FAIL: test_import_and_export (__main__.GPGTestCase)
Test that key import and export works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gnupg.py", line 824, in test_import_and_export
    self.assertEqual(result.summary(), '2 imported')
AssertionError: '1 imported' != '2 imported'

======================================================================
FAIL: test_import_only (__main__.GPGTestCase)
Test that key import works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gnupg.py", line 872, in test_import_only
    self.assertTrue(is_list_with_len(public_keys, 2), '2-element list expected')
AssertionError: 2-element list expected

======================================================================
FAIL: test_passing_paths (__main__.GPGTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gnupg.py", line 1456, in test_passing_paths
    self.assertEqual(result.imported, 2)
AssertionError: 1 != 2

======================================================================
FAIL: test_scan_keys (__main__.GPGTestCase)
Test that external key files can be scanned
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gnupg.py", line 698, in test_scan_keys
    self.assertEqual(uids, expected)
AssertionError: Items in the first set but not the second:
u'redacted'
Items in the second set but not the first:
'Gary Gross (A test user) <gary.gross@gamma.com>'
'Danny Davis (A test user) <danny.davis@delta.com>'

======================================================================
FAIL: test_scan_keys_mem (__main__.GPGTestCase)
Test that external keys in memory can be scanned
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gnupg.py", line 716, in test_scan_keys_mem
    self.assertEqual(uids, expected)
AssertionError: Items in the first set but not the second:
u'redacted'
Items in the second set but not the first:
'Gary Gross (A test user) <gary.gross@gamma.com>'
'Danny Davis (A test user) <danny.davis@delta.com>'

======================================================================
FAIL: test_search_keys (__main__.GPGTestCase)
Test that searching for keys works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gnupg.py", line 1207, in test_search_keys
    self.assertEqual(0, r.returncode, 'Non-zero return code')
AssertionError: Non-zero return code

----------------------------------------------------------------------
Ran 39 tests in 58.843s

FAILED (failures=7)`

**Comment by vsajip** [comment]
Searching for keys sometimes fails because it relies on external servers. It can be discounted as not being a real problem. Since that is the only failure in the unmodified test suite, I think it can be ignored.

**Comment by vsajip** [comment]
As per [`tox.ini`](https://github.com/vsajip/python-gnupg/blob/6081e55ccb513a478a64eaa48e993cb40853851e/tox.ini#L16) and the [GitHub action step](https://github.com/vsajip/python-gnupg/blob/6081e55ccb513a478a64eaa48e993cb40853851e/.github/workflows/python-package.yml#L50), you should generally run the tests with the environment variable set: `NO_EXTERNAL_TESTS=1`
