### ISSUE TITLE
Decryption is always empty

### ISSUE THREAD

**Issue by bthorben** [vsajip/python-gnupg#216]
I am using python-gnupg for the follwing flow:

```
with tempfile.TemporaryDirectory() as tmpdir:
    gpg = gnupg.GPG(gnupghome=str(tmpdir), verbose=True)
    gpg.encoding = 'utf-8'
    input_data = gpg.gen_key_input(
        key_type='RSA',
        key_length=2048,
        name_real='Atfinity',
        name_comment='Generated by Atfinity',
        name_email='no-reply@atfinity.ch',
        passphrase='test',
    )
    key = gpg.gen_key(input_data)
    content = 'Encrypt this please'
    encrypted = gpg.encrypt_file(
        StringIO(content),
        recipients=key.fingerprint,
        always_trust=True,
        passphrase='test',
        sign=False
    )
    decrypted = gpg.decrypt(str(encrypted), always_trust=True, passphrase='test')
    self.assertEqual(content, str(decrypted))
```

However, the encrypted file is always empty. Went through the doc multiple times and I can't seem to figure out what I am doing wrong. I even followed your test cases and they seem very similar (you specify an output file). 

Is this a bug or am I doing something wrong?

**Comment by bthorben** [comment]
This works with BytesIO instead of StringIO:

```
content = 'Encrypt this please'
            encrypted = gpg.encrypt_file(
                BytesIO(content.encode()),
                recipients=key.fingerprint,
                always_trust=True,
                passphrase='test',
                sign=False
            )
```
It would be handle if both situations work or the documentation makes it 100% clear this would not work.

**Comment by bthorben** [comment]
See also https://stackoverflow.com/questions/75351398/python-gnupg-always-returning-empty-decryption-result

**Comment by vsajip** [comment]
Not sure why you reopened this. Data should always be considered as binary at the level of encryption and decryption, and you can encode and decode as necessary at a higher level if you're actually dealing with text. I don't believe this needs specially documenting for `python-gnupg`, as it's a general thing relating to how data is passed between processes.

**Comment by bthorben** [comment]
Thanks for the explanation.

I would still add, that here I would even immediately see that data is flowing between processes. I read the documentation carefully and obviously could not figure this out. 

I don't see the harm in mentioning this in the documentation.

About the reopening: I closed this accidentally.

**Comment by vsajip** [comment]
Would you like to propose some additional clarifying wording and indicate where it should be added in the documentation?
