### ISSUE TITLE
Add detached signature verification with both a message and its signature located in memory

### ISSUE THREAD

**Issue by ghost** [vsajip/python-gnupg#218]
Dear colleagues,

I'm developing a tool based on `python-gnupg` and I want to store a message and its detached signature in SQL database. Unfortunately, I can't find a method to verify it easily. Both `gpg.verify` and `gpg.verify_file`, as I can see, do not provide a "beautiful" solution for my purpose.

Could you help me with that?

**Comment by vsajip** [comment]
This is not a place for a discussion - please use the mailing list.
