### ISSUE TITLE
Clearsign verification does not provide signed data in `gnupg.Verify` object

### ISSUE THREAD

**Issue by ghost** [vsajip/python-gnupg#219]
Dear colleagues,

I'm stuck with the following problem: when I try to get data of a message which was clear-signed, `gnupg.Verify` returns an empty bytestring.

Example:

```bash
echo "SOME DATA" | gpg --homedir=.gnupg --clear-sign -u 64F91892C853E3AE47609404FFA52E01D38A94DC > signed.asc
```

```python
import gnupg
gpg = gnupg.GPG(gnupghome=".gnupg")
with open('signed.asc', 'rt') as f: data = f.read()
verified = gpg.verify(data)
verified.sig_info # {'IeGsobx65o0nIdGq7wyCqjqthTc': {'creation_date': '2023-03-03', 'timestamp': '1677825386', 'keyid': 'FFA52E01D38A94DC', 'username': 'erteret <rr@rr.tt>', 'status': 'signature valid', 'fingerprint': '64F91892C853E3AE47609404FFA52E01D38A94DC', 'expiry': '0', 'pubkey_fingerprint': '64F91892C853E3AE47609404FFA52E01D38A94DC', 'trust_level': 3, 'trust_text': 'TRUST_FULLY'}}
verified.status # 'signature valid'
verified.data # b''
```

The same pipeline with sign and encrypt:

```bash
echo "SOME DATA" | gpg --homedir=.gnupg -sear DD13BD5B95E4E5F0F5DE817803DCFF8D7F78367F -u 64F91892C853E3AE47609404FFA52E01D38A94DC > signed.asc
```

```python
import gnupg
gpg = gnupg.GPG(gnupghome=".gnupg")
with open('signed.asc', 'rt') as f: data = f.read()
verified = gpg.decrypt(data)
verified.ok # True
verified.sig_info # {'SUH9UA0L/b9GNn8dDAi0MnyCZ2U': {'creation_date': '2023-03-03', 'timestamp': '1677826000', 'keyid': 'FFA52E01D38A94DC', 'username': 'erteret <rr@rr.tt>', 'status': 'signature valid', 'fingerprint': '64F91892C853E3AE47609404FFA52E01D38A94DC', 'expiry': '0', 'pubkey_fingerprint': '64F91892C853E3AE47609404FFA52E01D38A94DC', 'trust_level': 3, 'trust_text': 'TRUST_FULLY'}}
verified.data # b'SOME DATA\n'
```

Can you help me? Maybe I'm looking for the data in a wrong place?

---

Versions:

- python-gnupg: 0.4.9
- python: 3.10.6
- Ubuntu 22.04.2 LTS [jammy]

**Comment by Emru1** [comment]
Same problem here, how can I access raw data after signature verification?

**Comment by vsajip** [comment]
The verification process itself doesn't produce any output other than valid/invalid, so that's why there's no data. Of course when you do a decryption operation, there _is_ data to be returned. When you do a clearsign, you send the data as well as the signature to the recipient, so that they can verify the signature against the data.

**Comment by pptman** [comment]
I was looking to do this too and found the following would work:
```
import gnupg
gpg = gnupg.GPG(gnupghome=".gnupg")
with open('signed.asc', 'rt') as f: data = f.read()
verified = gpg.verify(data, extra_args=['--output', '-'])
verified.sig_info # {'IeGsobx65o0nIdGq7wyCqjqthTc': {'creation_date': '2023-03-03', 'timestamp': '1677825386', 'keyid': 'FFA52E01D38A94DC', 'username': 'erteret <rr@rr.tt>', 'status': 'signature valid', 'fingerprint': '64F91892C853E3AE47609404FFA52E01D38A94DC', 'expiry': '0', 'pubkey_fingerprint': '64F91892C853E3AE47609404FFA52E01D38A94DC', 'trust_level': 3, 'trust_text': 'TRUST_FULLY'}}
verified.status # 'signature valid'
verified.data # b'SOME DATA\n'
```
The `extra_args` are passed to gpg and in this case write the output to `STDOUT` where they are picked up in the returned `verify` data structure.  Likewise you can output the original file contents to a new file with the signing features stripped.

**Comment by vsajip** [comment]
Thanks for the idea, Mark. I've added [a section to the documentation](https://docs.red-dove.com/python-gnupg/index.html#getting-the-signed-data-out-while-verifying).

**Comment by vsajip** [comment]
As the suggestion from @pptman meets the requirement, I propose to close this issue.
