### ISSUE TITLE
I'd like to read output as a stream

### ISSUE THREAD

**Issue by stuartf** [vsajip/python-gnupg#225]
**Is your feature request related to a problem? Please describe.**

I'm decrypting large files and sometimes have to modify lines before writing them into a DB. Having to keep the entire decrypted file in memory isn't feasible.

**Describe the solution you'd like**

If I could pass a stream object like `output=io.StringIO()` and read from that my problem would be solved.

**Describe alternatives you've considered**

I'm currently doing this using Popen and reading process.stdout, but would like to use this library instead of having to manage all the code surrounding running gpg as a subprocess.

**Additional context**

n/a

**Comment by vsajip** [comment]
Review the [current documentation](https://gnupg.readthedocs.io/en/latest/) and look for mentions of `on_data`. It sounds like that's what you need. It's not _exactly_ what you're asking for, but should meet the needs you describe.

**Comment by stuartf** [comment]
Ah, nice. `on_data` looks like it should work for my purposes.

**Comment by vsajip** [comment]
OK, I'll close this issue, then!
