### ISSUE TITLE
gpg returned a non-zero error code: 2

### ISSUE THREAD

**Issue by mdvb01** [vsajip/python-gnupg#226]
While decrypting the file getting below error :

gpg returned a non-zero error code: 2
Error :[GNUPG:] NODATA 2
gpg: decrypt_message failed: Unknown system error
status.ok : False
status.status : no data was provided

python-gnupg version - 0.4.6
Below is the code snippet : 
gpg = gnupg.GPG(gnupghome="/tmp", gpgbinary="/usr/bin/gpg")
self.ssh_passphrase = "*****"
## Key imported successfully (Privatekey)
 status = gpg.decrypt_file(
                    f, passphrase=self.ssh_passphrase, output=local_decrypted_file_path
                )

**Comment by vsajip** [comment]
This is something to do with the underlying `gpg` environment, and not `python-gnupg` specifically. You will get the same result if you invoke `gpg` from a terminal to perform the same operation. I propose to close this issue unless it's clearly a `python-gnupg` issue.

**Comment by vsajip** [comment]
Closing, as no feedback received.
