### ISSUE TITLE
Which is the site for the docs?

### ISSUE THREAD

**Issue by raffaelemancuso** [vsajip/python-gnupg#227]
[GitHub](https://github.com/vsajip/python-gnupg) points to [red-dove.com](https://docs.red-dove.com/python-gnupg/) for the docs, while [PyPi](https://pypi.org/project/python-gnupg/) points to [ReadTheDocs](https://gnupg.readthedocs.io/)

**Comment by vsajip** [comment]
Both sites are kept up to date - you can use which ever you prefer. Only the documentation style/theme should be different.
