### ISSUE TITLE
output argument for encrypt

### ISSUE THREAD

**Issue by raffaelemancuso** [vsajip/python-gnupg#228]
Why not add an `output` argument also to the `encrypt` function (like the one which is already in the `encrypt_file` function) to encrypt a stream and save directly to a file?

**Comment by vsajip** [comment]
It's there, see this line in the `encrypt` docstring. Perhaps it's missing from the documentation - I will check.
https://github.com/vsajip/python-gnupg/blob/7f7b32d2fee9c0608f83e751e17b10c19c302413/gnupg.py#L2056

**Comment by raffaelemancuso** [comment]
From the [docs](https://docs.red-dove.com/python-gnupg/#encryption) looks like it's only for `encrypt_file`

**Comment by vsajip** [comment]
Yes, I see that - will correct that.
