### ISSUE TITLE
Runtime Error: GnuPG is not installed.

### ISSUE THREAD

**Issue by codekid20** [vsajip/python-gnupg#238]
Hey Everyone,
I am trying to import gnupg in my python code, but when i am running the code i am getting this Runtime error mentioned below.

Runtime Error: GnuPg is not installed.

I installed package by running "pip install python-gnupg" 
Here is how i imported and initialized the module : 

import gnupg
gpg = gnupg.GPG()

**Comment by vsajip** [comment]
In addition to the `python-gnupg` package, you need to ensure GnuPG itself is installed. Visit https://gnupg.org/ for information on how to do that.
