### ISSUE TITLE
Decrypted string is logged in plain text when log level is DEBUG

### ISSUE THREAD

**Issue by danhje** [vsajip/python-gnupg#239]
**Is your feature request related to a problem? Please describe.**
Decrypted secret is logged when log level is DEBUG, meaning it can easily end up in CI/CD pipeline logs or show up when screen sharing.

**Describe the solution you'd like**
Remove [this](https://github.com/vsajip/python-gnupg/blob/efb2043730b6db890daa20344eea4cd8592c8de6/gnupg.py#L2200) line.

**Comment by danhje** [comment]
Thanks for the quick response! Hope to see a release in the not-too-distant future 😊

**Comment by vsajip** [comment]
I'm currently planning to release some time next month.
