### ISSUE TITLE
Gnupg return code 2 while trusting key

### ISSUE THREAD

**Issue by Nichokas** [vsajip/python-gnupg#243]
**Describe the bug**
The Python script should be updating the trust level, but it might be me; I can’t think of any way to fix it." 
**To Reproduce**
```python
gpg = gnupg.GPG()
cert="DACCF18B6800FCD0"
trust_levels = [("TRUST_FULLY", "Trusted"),("TRUST_NEVER", "NOT Trusted")]
trust = radiolist_dialog(
    title="Select a trust level",
    text="Selec a trust level for the selected key:",
    values=trust_levels
).run()
if trust:
    gpg.trust_keys(cert, trust)
```
File "/home/nichokas/Documents/gpg4td/venv/lib/python3.12/site-packages/gnupg.py", line 2276, in trust_keys
    raise ValueError('gpg returned an error - return code %d' % p.returncode)
ValueError: gpg returned an error - return code 2

**Expected behavior**
Certificate with changed trust

**Environment**
 - fedora linux 40, python 3.12
 - v0.5.3

**Comment by vsajip** [comment]
I suggest you enable logging and look at the portion of the log relating to the `trust_keys()` call. If you don't spot an obvious problem, post that portion of the log here.

**Comment by vsajip** [comment]
I've marked this issue as pending, will close if no further feedback received soon.
